replicaCount: 1

global:
  gcp:
    projectId: ecommerce-microservice-53
  image:
    registry: us-central1-docker.pkg.dev
    project: ecommerce-microservice-53
    repository: ecommerce-repo

image:
  name: audit-service
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

env:
  KAFKA_BROKERS: "kafka-bootstrap.kafka.svc.cluster.local:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.platform-observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "audit-service"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true
  name: audit-service-sa
  gcpServiceAccount: audit-service@ecommerce-microservice-53.iam.gserviceaccount.com
