apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: platform-argocd
spec:
  description: "Microservices"
  sourceRepos:
    - "https://github.com/Moiz-Ali-Moomin/microservice-ecommerce-gcp-cloud-gke-setup"
  destinations:
    - namespace: "apps-*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: networking.k8s.io
      kind: NetworkPolicy
