replicaCount: 1
image:
  repository: ""
  tag: latest
service:
  type: ClusterIP
  port: 8080
env:
  KAFKA_BROKERS: "kafka-bootstrap.kafka.svc.cluster.local:9092"
resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# -------------------
# GCP WORKLOAD IDENTITY
# -------------------
gcp:
  projectId: "ecommerce-microservice-53"
  serviceAccount:
    name: analytics-ingest-service

# -------------------
# GLOBAL CONFIGURATION
# -------------------
global:
  gcp:
    projectId: "ecommerce-microservice-53"
  image:
    registry: "us-central1-docker.pkg.dev"
    project: "ecommerce-microservice-53"
    repository: "ecommerce-repo"

image:
  name: 'analytics-ingest-service'
  tag: 'latest'

serviceAccount:
  create: true
  name: 'analytics-ingest-service-sa'
  gcpServiceAccount: 'analytics-ingest-service'
