apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: platform-argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/your-org/ecommerce-platform.git
    targetRevision: HEAD
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
