replicaCount: 1

global:
  gcp:
    projectId: ecommerce-microservice-53
  image:
    registry: us-central1-docker.pkg.dev
    project: ecommerce-microservice-53
    repository: ecommerce-repo

image:
  name: user-service
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

env: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

serviceAccount:
  create: true
  name: user-service-sa
  gcpServiceAccount: user-service@ecommerce-microservice-53.iam.gserviceaccount.com
