replicaCount: 1 # High availability for landing
image:
  repository: us-central1-docker.pkg.dev/ecommerce-microservice-53/ecommerce-repo/landing-service
  tag: latest
service:
  type: ClusterIP
  port: 8080
env:
  KAFKA_BROKERS: "kafka-bootstrap.kafka.svc.cluster.local:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.platform-observability.svc.cluster.local:4317
  OTEL_SERVICE_NAME: landing-service
resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 1000m # Burst header
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
