apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "analytics-ingest-service.fullname" . }}
  labels:
    {{- include "analytics-ingest-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "analytics-ingest-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "analytics-ingest-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ include "analytics-ingest-service.image" . }}"
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
