apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gcp.serviceAccount.name }}-sa
  annotations:
    iam.gke.io/gcp-service-account: {{ include "conversion-webhook.serviceAccountEmail" . }}
