replicaCount: 1

autoscaling:
  enabled: false

global:
  image:
    registry: us-central1-docker.pkg.dev
    project: ecommerce-microservice-53
    repository: ecommerce-repo

image:
  name: storefront-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  PRODUCT_SERVICE_URL: "http://product-service.apps-core.svc.cluster.local:8080"
  CART_SERVICE_URL: "http://cart-service.apps-core.svc.cluster.local:8080"
  OFFER_SERVICE_URL: "http://offer-service.apps-core.svc.cluster.local:8080"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.platform-observability.svc.cluster.local:4317"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

serviceAccount:
  create: true
  name: storefront-service-sa
  gcpServiceAccount: storefront-service@ecommerce-microservice-53.iam.gserviceaccount.com
