# infra/spark/values.yaml
# Values for googlecloudplatform/spark-on-k8s-operator

image:
  repository: gcr.io/spark-operator/spark-operator
  tag: v1beta2-1.3.8-3.1.1

webhook:
  enable: true

# Operator Resources (Hardened)
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

resourceQuota:
  enable: false

# Prometheus monitoring for the operator
monitoring:
  prometheus:
    enable: true
