replicaCount: 1

autoscaling:
  enabled: false

global:
  image:
    registry: REGISTRY_REGION-docker.pkg.dev
    project: PROJECT_ID
    repository: ecommerce-repo

image:
  name: api-gateway
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  KAFKA_BROKERS: "kafka-bootstrap.kafka.svc.cluster.local:9092"
  AUTH_SERVICE_URL: "http://auth-service.components.svc.cluster.local:8080"
  USER_SERVICE_URL: "http://user-service.components.svc.cluster.local:8080"
  OFFER_SERVICE_URL: "http://offer-service.components.svc.cluster.local:8080"
  CART_SERVICE_URL: "http://cart-service.components.svc.cluster.local:8080"
  STOREFRONT_SERVICE_URL: "http://storefront-service.components.svc.cluster.local:3000"
  REDIS_ADDR: "redis-master.data.svc.cluster.local:6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.platform-observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "api-gateway"

envSecrets:
  POSTGRES_DSN:
    name: "api-gateway-secrets"
    key: "postgres-dsn"

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true
  name: api-gateway
  gcpServiceAccount: api-gateway@PROJECT_ID.iam.gserviceaccount.com
