replicaCount: 1

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: true
  minAvailable: 1

global:
  image:
    registry: us-central1-docker.pkg.dev
    project: ecommerce-project
    repository: ecommerce-repo

image:
  name: api-gateway
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  AUTH_SERVICE_URL: "http://auth-service.apps-core.svc.cluster.local:8080"
  USER_SERVICE_URL: "http://user-service.apps-core.svc.cluster.local:8080"
  OFFER_SERVICE_URL: "http://offer-service.apps-core.svc.cluster.local:8080"
  CART_SERVICE_URL: "http://cart-service.apps-core.svc.cluster.local:8080"
  STOREFRONT_SERVICE_URL: "http://storefront-service.apps-public.svc.cluster.local:3000"
  LANDING_SERVICE_URL: "http://landing-service.apps-public.svc.cluster.local:8080"
  REDIRECT_SERVICE_URL: "http://redirect-service.apps-public.svc.cluster.local:8080"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.platform-observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "api-gateway"



resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true
  name: api-gateway
  gcpServiceAccount: api-gateway@ecommerce-project.iam.gserviceaccount.com
