replicaCount: 1

autoscaling:
  enabled: false

global:
  image:
    registry: us-central1-docker.pkg.dev
    project: ecommerce-microservice-53
    repository: ecommerce-repo

image:
  name: auth-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  # Infrastructure Hosts
  DB_HOST: "postgres-primary.data.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "ecommerce_db"
  REDIS_HOST: "redis-master.data.svc.cluster.local"
  REDIS_PORT: "6379"

  # Observability
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.platform-observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "auth-service"

  # Optional Kafka
  KAFKA_BROKERS: "kafka-bootstrap.kafka.svc.cluster.local:9092"

envSecrets:
  JWT_SECRET:
    name: auth-jwt-secret
    key: JWT_SECRET
  DB_USER:
    name: auth-service-secrets
    key: db-user
  DB_PASSWORD:
    name: auth-service-secrets
    key: db-password
  REDIS_PASSWORD:
    name: auth-redis-secret
    key: REDIS_PASSWORD

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true
  name: auth-service-sa
  gcpServiceAccount: auth-service@ecommerce-microservice-53.iam.gserviceaccount.com
