replicaCount: 1

global:
  gcp:
    projectId: ecommerce-microservice-53
  image:
    registry: us-central1-docker.pkg.dev
    project: ecommerce-microservice-53
    repository: ecommerce-repo

image:
  name: feature-flag-service
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

env:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.platform-observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "feature-flag-service"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: true
  name: feature-flag-service-sa
  gcpServiceAccount: feature-flag-service@ecommerce-microservice-53.iam.gserviceaccount.com
