replicaCount: 1

autoscaling:
  enabled: false

global:
  image:
    registry: us-central1-docker.pkg.dev
    project: ecommerce-microservice-53
    repository: ecommerce-repo

image:
  name: conversion-webhook
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  KAFKA_BROKERS: "kafka-bootstrap.kafka.svc.cluster.local:9092"
  CLICKBANK_SECRET_KEY: "change_me_in_prod"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.platform-observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "conversion-webhook"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

serviceAccount:
  create: true
  name: conversion-webhook-sa
  gcpServiceAccount: conversion-webhook@ecommerce-microservice-53.iam.gserviceaccount.com
