apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter
  namespace: platform-observability
  labels:
    prometheus: k8s
    role: node-exporter
spec:
  staticConfigs:
    - targets:
        - node-exporter.platform-observability.svc.cluster.local:9100
  metricsPath: /metrics
  scheme: http
